name: Github To Registry
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ github.token }}
        image-name: echo-server
        dockerfile: Dockerfile
